### ISSUE TITLE
If user in exits on "UAT" of enrolment and EAC with two different "Time zone" example: In EAC "Asia/jakarta" and in enrolment "Asia/Kolkata" and now user try to login in "Qa" environment then user gets the "Default" time zone. User should get the "Asia/jakarta"  time zone.

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel18#66]
If user in exits on "UAT" of enrolment and EAC with two different "Time zone" example: In EAC "Asia/jakarta" and in enrolment "Asia/Kolkata" and now user try to login in "Qa" environment then user gets the "Default" time zone. User should get the "Asia/jakarta"  time zone.

**Comment by dharamveerSanodiya** [comment]
Again getting the similar issue but this time we have some more finding.

If we register the user in EAC and then try to update the timezone information from https://access.uat.oup.com/eac/profile.htm then the registration information web service is not getting the updated data since this update is done by EAC UI.

But if we update the timezone or other information from Enrolment Tool UAT then the registration information web service is getting the updated data since the update is done directly by web service.

Noticed the issue during testing and this is related to following email we had before a year.

**Comment by NitinLeuva** [comment]
Subrata,

Again getting the similar issue but this time we have some more finding.

If we register the user in EAC and then try to update the timezone information from https://access.uat.oup.com/eac/profile.htm then the registration information web service is not getting the updated data since this update is done by EAC UI.

But if we update the timezone or other information from Enrolment Tool UAT then the registration information web service is getting the updated data since the update is done directly by web service.

Noticed the issue during testing and this is related to following email we had before a year.

Nitin

**Comment by NitinLeuva** [comment]
Rahul this is not an issue at our end, this is due to issue in EAC. Please update the timezone with webservices or another Enrolment Tool instance.

**Comment by rahul-kumar11** [comment]
Closing according above comment.
